### ISSUE TITLE
Singular `transition` property doesn't work

### ISSUE THREAD

**Issue by jasny** [legalthings/workflow-engine#17]
The following doesn't work. The `transition` property is ignored.

```yaml
states:
  :initial:
    action: complete
    transition: :success
```

Only an array of transitions work.

```yaml
states:
  :initial:
    action: complete
    transitions:
      - transition: :success
```

Similar to `action`, you should be able to give a single transition if there is only one. (pretty json view)
